services:
  database:
    image: 'postgres:16.0-alpine3.18'
    container_name: 'postgres-tbn'
    env_file:
      - ../../.env.development
    ports:
      - '5432:5432'
  mailcatcher:
    container_name: 'mailcatcher-tbn'
    image: 'sj26/mailcatcher'
    ports:
      - '1025:1025'
      - '1080:1080'
